import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-medicare-cost-report-reimbursement-recovery",
  "engine": "recovery",
  "title": "Medicare Cost Report Reimbursement Recovery",
  "shortTitle": "Medicare Reimbursement OS",
  "tagline": "Maximize supported Medicare reimbursement while preserving audit defensibility",
  "industry": "Medicare Reimbursement Compliance",
  "uiPort": 4552,
  "apiPort": 5552,
  "accent": "#0369a1",
  "currency": "USD",
  "primaryOutcome": "Supported Medicare reimbursement recovered through accurate cost allocation and filing evidence",
  "valueNarrative": "Unify cost reports, trial balances, statistics, bad-debt support, wage data, and audit correspondence into one recovery system.",
  "calculation": {
    "actualKey": "reimbursedAmount",
    "expectedKey": "allowableAmount",
    "actualLabel": "Recorded reimbursement",
    "expectedLabel": "Supported reimbursement",
    "varianceLabel": "Potential reimbursement recovery",
    "direction": "expected-minus-actual",
    "finding": "Cost-report schedules and supporting statistics indicate additional Medicare reimbursement opportunity.",
    "actions": [
      "Reconcile the trial balance to cost-report schedules",
      "Validate allocation statistics and related-party treatment",
      "Complete bad-debt and reimbursement evidence",
      "File or reopen within the applicable deadline"
    ]
  }
},[
feature("provider-and-filing-year-registry","MRO01","Provider and filing-year registry","Reconcile provider and filing-year registry using CMS cost-report instructions, trial balances, allocation statistics, PS&R, bad debt, wage index, and audit support.","Produce a governed provider and filing-year registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["providerNumber","CMS Provider Number","text","19-8421"],["costReportYear","Cost Report Year","text","2025"],["reimbursedAmount","Recorded Reimbursement","currency",4820000],["allowableAmount","Supported Allowable Amount","currency",5375000]],{amountField:"reimbursedAmount",subjects:["Acute care hospital","Critical access hospital","Skilled nursing facility","Home health agency","Hospice provider"]}),
feature("trial-balance-import-and-mapping","MRO02","Trial-balance import and mapping","Reconcile trial-balance import and mapping using CMS cost-report instructions, trial balances, allocation statistics, PS&R, bad debt, wage index, and audit support.","Produce a governed trial-balance import and mapping decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["providerNumber","CMS Provider Number","text","19-8421"],["costReportYear","Cost Report Year","text","2025"],["reimbursedAmount","Recorded Reimbursement","currency",4820000],["allowableAmount","Supported Allowable Amount","currency",5375000]],{amountField:"reimbursedAmount",subjects:["Acute care hospital","Critical access hospital","Skilled nursing facility","Home health agency","Hospice provider"]}),
feature("cost-center-classification","MRO03","Cost-center classification","Reconcile cost-center classification using CMS cost-report instructions, trial balances, allocation statistics, PS&R, bad debt, wage index, and audit support.","Produce a governed cost-center classification decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["providerNumber","CMS Provider Number","text","19-8421"],["costReportYear","Cost Report Year","text","2025"],["reimbursedAmount","Recorded Reimbursement","currency",4820000],["allowableAmount","Supported Allowable Amount","currency",5375000]],{amountField:"reimbursedAmount",subjects:["Acute care hospital","Critical access hospital","Skilled nursing facility","Home health agency","Hospice provider"]}),
feature("overhead-step-down-allocation","MRO04","Overhead step-down allocation","Reconcile overhead step-down allocation using CMS cost-report instructions, trial balances, allocation statistics, PS&R, bad debt, wage index, and audit support.","Produce a governed overhead step-down allocation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["providerNumber","CMS Provider Number","text","19-8421"],["costReportYear","Cost Report Year","text","2025"],["reimbursedAmount","Recorded Reimbursement","currency",4820000],["allowableAmount","Supported Allowable Amount","currency",5375000]],{amountField:"reimbursedAmount",subjects:["Acute care hospital","Critical access hospital","Skilled nursing facility","Home health agency","Hospice provider"]}),
feature("medicare-utilization-statistics","MRO05","Medicare utilization statistics","Reconcile medicare utilization statistics using CMS cost-report instructions, trial balances, allocation statistics, PS&R, bad debt, wage index, and audit support.","Produce a governed medicare utilization statistics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["providerNumber","CMS Provider Number","text","19-8421"],["costReportYear","Cost Report Year","text","2025"],["reimbursedAmount","Recorded Reimbursement","currency",4820000],["allowableAmount","Supported Allowable Amount","currency",5375000]],{amountField:"reimbursedAmount",subjects:["Acute care hospital","Critical access hospital","Skilled nursing facility","Home health agency","Hospice provider"]}),
feature("psandr-reconciliation","MRO06","PS&R reconciliation","Reconcile ps&r reconciliation using CMS cost-report instructions, trial balances, allocation statistics, PS&R, bad debt, wage index, and audit support.","Produce a governed ps&r reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["providerNumber","CMS Provider Number","text","19-8421"],["costReportYear","Cost Report Year","text","2025"],["reimbursedAmount","Recorded Reimbursement","currency",4820000],["allowableAmount","Supported Allowable Amount","currency",5375000]],{amountField:"reimbursedAmount",subjects:["Acute care hospital","Critical access hospital","Skilled nursing facility","Home health agency","Hospice provider"]}),
feature("medicare-bad-debt-recovery","MRO07","Medicare bad-debt recovery","Reconcile medicare bad-debt recovery using CMS cost-report instructions, trial balances, allocation statistics, PS&R, bad debt, wage index, and audit support.","Produce a governed medicare bad-debt recovery decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["providerNumber","CMS Provider Number","text","19-8421"],["costReportYear","Cost Report Year","text","2025"],["reimbursedAmount","Recorded Reimbursement","currency",4820000],["allowableAmount","Supported Allowable Amount","currency",5375000]],{amountField:"reimbursedAmount",subjects:["Acute care hospital","Critical access hospital","Skilled nursing facility","Home health agency","Hospice provider"]}),
feature("dsh-and-uncompensated-care-support","MRO08","DSH and uncompensated-care support","Reconcile dsh and uncompensated-care support using CMS cost-report instructions, trial balances, allocation statistics, PS&R, bad debt, wage index, and audit support.","Produce a governed dsh and uncompensated-care support decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["providerNumber","CMS Provider Number","text","19-8421"],["costReportYear","Cost Report Year","text","2025"],["reimbursedAmount","Recorded Reimbursement","currency",4820000],["allowableAmount","Supported Allowable Amount","currency",5375000]],{amountField:"reimbursedAmount",subjects:["Acute care hospital","Critical access hospital","Skilled nursing facility","Home health agency","Hospice provider"]}),
feature("ime-and-gme-reimbursement","MRO09","IME and GME reimbursement","Reconcile ime and gme reimbursement using CMS cost-report instructions, trial balances, allocation statistics, PS&R, bad debt, wage index, and audit support.","Produce a governed ime and gme reimbursement decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["providerNumber","CMS Provider Number","text","19-8421"],["costReportYear","Cost Report Year","text","2025"],["reimbursedAmount","Recorded Reimbursement","currency",4820000],["allowableAmount","Supported Allowable Amount","currency",5375000]],{amountField:"reimbursedAmount",subjects:["Acute care hospital","Critical access hospital","Skilled nursing facility","Home health agency","Hospice provider"]}),
feature("wage-index-data-validation","MRO10","Wage-index data validation","Reconcile wage-index data validation using CMS cost-report instructions, trial balances, allocation statistics, PS&R, bad debt, wage index, and audit support.","Produce a governed wage-index data validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["providerNumber","CMS Provider Number","text","19-8421"],["costReportYear","Cost Report Year","text","2025"],["reimbursedAmount","Recorded Reimbursement","currency",4820000],["allowableAmount","Supported Allowable Amount","currency",5375000]],{amountField:"reimbursedAmount",subjects:["Acute care hospital","Critical access hospital","Skilled nursing facility","Home health agency","Hospice provider"]}),
feature("related-party-cost-review","MRO11","Related-party cost review","Reconcile related-party cost review using CMS cost-report instructions, trial balances, allocation statistics, PS&R, bad debt, wage index, and audit support.","Produce a governed related-party cost review decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["providerNumber","CMS Provider Number","text","19-8421"],["costReportYear","Cost Report Year","text","2025"],["reimbursedAmount","Recorded Reimbursement","currency",4820000],["allowableAmount","Supported Allowable Amount","currency",5375000]],{amountField:"reimbursedAmount",subjects:["Acute care hospital","Critical access hospital","Skilled nursing facility","Home health agency","Hospice provider"]}),
feature("cost-report-schedule-preparation","MRO12","Cost-report schedule preparation","Reconcile cost-report schedule preparation using CMS cost-report instructions, trial balances, allocation statistics, PS&R, bad debt, wage index, and audit support.","Produce a governed cost-report schedule preparation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["providerNumber","CMS Provider Number","text","19-8421"],["costReportYear","Cost Report Year","text","2025"],["reimbursedAmount","Recorded Reimbursement","currency",4820000],["allowableAmount","Supported Allowable Amount","currency",5375000]],{amountField:"reimbursedAmount",subjects:["Acute care hospital","Critical access hospital","Skilled nursing facility","Home health agency","Hospice provider"]}),
feature("desk-review-request-management","MRO13","Desk-review request management","Reconcile desk-review request management using CMS cost-report instructions, trial balances, allocation statistics, PS&R, bad debt, wage index, and audit support.","Produce a governed desk-review request management decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["providerNumber","CMS Provider Number","text","19-8421"],["costReportYear","Cost Report Year","text","2025"],["reimbursedAmount","Recorded Reimbursement","currency",4820000],["allowableAmount","Supported Allowable Amount","currency",5375000]],{amountField:"reimbursedAmount",subjects:["Acute care hospital","Critical access hospital","Skilled nursing facility","Home health agency","Hospice provider"]}),
feature("reopening-and-appeal-workflow","MRO14","Reopening and appeal workflow","Reconcile reopening and appeal workflow using CMS cost-report instructions, trial balances, allocation statistics, PS&R, bad debt, wage index, and audit support.","Produce a governed reopening and appeal workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["providerNumber","CMS Provider Number","text","19-8421"],["costReportYear","Cost Report Year","text","2025"],["reimbursedAmount","Recorded Reimbursement","currency",4820000],["allowableAmount","Supported Allowable Amount","currency",5375000]],{amountField:"reimbursedAmount",subjects:["Acute care hospital","Critical access hospital","Skilled nursing facility","Home health agency","Hospice provider"]}),
feature("reimbursement-outcome-analytics","MRO15","Reimbursement outcome analytics","Reconcile reimbursement outcome analytics using CMS cost-report instructions, trial balances, allocation statistics, PS&R, bad debt, wage index, and audit support.","Produce a governed reimbursement outcome analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["providerNumber","CMS Provider Number","text","19-8421"],["costReportYear","Cost Report Year","text","2025"],["reimbursedAmount","Recorded Reimbursement","currency",4820000],["allowableAmount","Supported Allowable Amount","currency",5375000]],{amountField:"reimbursedAmount",subjects:["Acute care hospital","Critical access hospital","Skilled nursing facility","Home health agency","Hospice provider"]})
]);
